name: NuGet

on:
  push:
    tags:
      - 'v*'

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}
    - name: Create Package
      run: dotnet pack ./MbDotNet/MbDotNet.csproj -c Release -o packages
    - name: Archive production artifacts
      uses: actions/upload-artifact@v7
      with:
        name: packages
        path: packages
